### ISSUE TITLE
How to install pyasm 

### ISSUE THREAD

**Issue by Star-Vampire** [SuperStormer/pyasm#1]
how to install pyasm in termux

**Comment by SuperStormer** [comment]
Install python, pip and git through the termux package manager - there should be plenty of online guides for this. Then install pyasm through pip:
```
pip install git+https://github.com/SuperStormer/pyasm.git
```

**Comment by Star-Vampire** [comment]
Im faceing this error
pip install git+https://github.com/SuperStormer/pyasm.git
install this add type pyasm and showing this error

**Comment by SuperStormer** [comment]
What is the error message?
